AWSTemplateFormatVersion: '2010-09-09'
Description: 'A proof-of-concept for message passing using SNS and SQS to communicate between to node.js services.'
Parameters:
  MyPublishUserPassword:
    NoEcho: 'true'
    Type: String
    Description: Password for the IAM user MyPublishUser
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  MyQueueUserPassword:
    NoEcho: 'true'
    Type: String
    Description: Password for the IAM user MyQueueUser
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
Resources:
  AppEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint:
            Fn::GetAtt:
              - ServiceAQueue
              - Arn
          Protocol: sqs
        - Endpoint:
            Fn::GetAtt:
              - ServiceBQueue
              - Arn
          Protocol: sqs
  ServiceAQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  ServiceBQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  MyPublishUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password:
          Ref: MyPublishUserPassword
        PasswordResetRequired: false
  MyPublishUserKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: MyPublishUser
  MyPublishTopicGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: PublishGroup
      Policies:
        - PolicyName: MyTopicGroupPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  Ref: AppEventsTopic
  AddUserToMyPublishTopicGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName:
        Ref: MyPublishTopicGroup
      Users:
        - Ref: MyPublishUser
  MyQueueUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password:
          Ref: MyQueueUserPassword
        PasswordResetRequired: false
  MyQueueUserKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: MyQueueUser
  MyRDMessageQueueGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: QueueGroup
      Policies:
        - PolicyName: MyQueueGroupPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:DeleteMessageBatch
                  - sqs:ChangeMessageVisibility
                  - sqs:ChangeMessageVisibilityBatch
                Resource:
                  - Fn::GetAtt:
                      - ServiceAQueue
                      - Arn
                  - Fn::GetAtt:
                      - ServiceBQueue
                      - Arn
  AddUserToMyQueueGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName:
        Ref: MyRDMessageQueueGroup
      Users:
        - Ref: MyQueueUser
  MyQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: '*'
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: AppEventsTopic
      Queues:
        - Ref: ServiceAQueue
        - Ref: ServiceBQueue
Outputs:
  AppEventsTopicARN:
    Value:
      Ref: AppEventsTopic
  ServiceAQueueURL:
    Value:
      Ref: ServiceAQueue
  ServiceBQueueURL:
    Value:
      Ref: ServiceBQueue
  MyPublishUserInfo:
    Value:
      Fn::Join:
        - ' '
        - - 'ARN:'
          - Fn::GetAtt:
              - MyPublishUser
              - Arn
          - 'Access Key:'
          - Ref: MyPublishUserKey
          - 'Secret Key:'
          - Fn::GetAtt:
              - MyPublishUserKey
              - SecretAccessKey
  MyQueueUserInfo:
    Value:
      Fn::Join:
        - ' '
        - - 'ARN:'
          - Fn::GetAtt:
              - MyQueueUser
              - Arn
          - 'Access Key:'
          - Ref: MyQueueUserKey
          - 'Secret Key:'
          - Fn::GetAtt:
              - MyQueueUserKey
              - SecretAccessKey
